### PR TITLE
Added option in sascfg for HTML 4.0 as alternative to HTLM 5.0

### PR DESCRIPTION
**Pull request by AlexiaJM**
Using PROC TEMPLATE with "ods html5" (HTML 5.0) can cause some problems
which do not happen when using "ods html" (HTML 4.0).  There are
probably other reasons why some people might want to use HTML 4.0 too.
I added an option in sascfg.py to be able to use HTML 4.0. So when people install saspy and set it up the first time, they can choose whether they want HTML 4.0 or 5.0.

This is my first time contributing to a project not of my own, I don't know if this is conform or not. The "output" variable could always be included in "SAS_config_options" instead of in "SAS_output_options". Tell me what you think.

### CODE REVIEW

**Comment by tomweber-sas** [comment]
Hey @AlexiaJM, First, thanks for contributing! Second, the code changes themselves seem fine, in general.

However, I believe that HTML5 is the only option which allows the graphics to be embedded inline in the html result, which is what the saspy interface is dependent upon in order to get the graphic results. I've changed the code to use html instead of html5, as you have, and it doesn't work for me.  I get none of the output from anything that produces graphics. 

Ah, I see now that only in the windows local mode of the IOM access methods, it does 'work'. in that all of the graphics are written to the current directory, which is resolved in the html document. For IOM not local on windows, this doesn't work as the graphics are written to the local directory where the IOM server is running (not where your python process is running), and there's no way for any of those files to be resolved on the client for the html document.

Can I ask what the problem was with html5 that isn't a problem with html? Perhaps solving that instead of not being able to have the graphics embedded in the html could be something I could look into?

Not denying this pull request, as it can work for the local windows scenario, but I'd like to explore it a little further and see if there's a more 'complete' solution to the problem. Can you show me the original problem you ran into with proc template?

Thanks!,
Tom

**Comment by AlexiaJM** [comment]
I agree that this is not ideal, I was only able to test it with IOM local and it clutters the workspace a lot but at least I get the proper template. Here's an example with proc template not working with HTML5:
(You can test this directly in SAS as this is a problem with SAS)

* Random dataset example;
data Fitness;
   input Age Weight Oxygen RunTime @@;
   datalines;
44 89.47 44.609 11.37    40 75.07 45.313 10.07
44 85.84 54.297  8.65    42 68.15 59.571  8.17
38 89.02 49.874   .      47 77.45 44.811 11.63
40 75.98 45.681 11.95    43 81.19 49.091 10.85
44 81.42 39.442 13.08    38 81.87 60.055  8.63
44 73.03 50.541 10.13    45 87.66 37.388 14.03
45 66.45 44.754 11.12    47 79.15 47.273 10.60
54 83.12 51.855 10.33    49 81.42 49.156  8.95
51 69.63 40.836 10.95    51 77.91 46.672 10.00
48 91.63 46.774 10.25    49 73.37   .    10.08
57 73.37 39.407 12.63    54 79.38 46.080 11.17
52 76.32 45.441  9.63    50 70.87 54.625  8.92
51 67.25 45.118 11.08    54 91.63 39.203 12.88
51 73.71 45.790 10.47    57 59.08 50.545  9.93
49 76.32   .      .      48 61.24 47.920 11.50
52 82.78 47.467 10.50
;

* Changing template to highlight p-values;

ods path(prepend) work.templat(update);
proc template;
	edit Base.Corr.StackedMatrix;
		column (RowName RowLabel) (Matrix) * (Matrix2) * (Matrix3);
		edit matrix2;
		cellstyle
                        _val_  = ._ as {backgroundcolor=CXEEEEEE},
			_val_  <=  0.001 as {backgroundcolor=pink},
			_val_  <=  0.01 as {backgroundcolor=yellow},
			_val_  <= 0.05 as {backgroundcolor=orange};
		end;
	end;
run;

ods _all_ close;

* This works;
ods html;
proc corr data=Fitness;
   var Weight Oxygen RunTime;
run;
ods html close;

* This does not work;
ods html5;
proc corr data=Fitness;
   var Weight Oxygen RunTime;
run;
ods html5 close;

**Comment by tomweber-sas** [comment]
Ok, I've reproduced this and entered a defect so this can get fixed (S1345765 - this is just for my reference). Hopefully this can be fixed in the next release so you won't need this work around. For now though, I'm ok with you being able to set it to html instead of html5 as you need that to work around this problem.

Can I ask for a couple tweaks to the implementation? When you get this value, can you default to html5 if it was not specified and if it was specified, validate it as being either html or html5.
Then, instead of replicating the whole odsopen/close strings with if statements to check the value of the option in the 4 or 5 places, you can just use the option directly in the existing odsopen/close strings.

odsopen  = b"ods listing close;ods "+ self.sascfg.output +" (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg; ods graphics on / outputfmt=png;\n"
odsclose = b"ods "+ self.sascfg.output +" (id=saspy_internal) close;ods listing;\n"

This is just a little cleaner as it's not replicating those strings in the various places they, and will just look a little cleaner.

With that, I'll be happy to merger this in for you. 

Thanks again for contributing!

**Comment by tomweber-sas** [comment]
Oh, and just another tweak in the comments to be explicit that this will only work in LOCAL mode, not in any of the remote scenarios. Thanks!

**Comment by jld23** [comment]
What will be the behavior if a user tries to use HTML in a remote scenario? Do we need to trap that case and throw and exception?

**Comment by tomweber-sas** [comment]
That would be easy enough to do.

**Comment by AlexiaJM** [comment]
Okay I did all that. I wasn't able to test it non-locally to make sure that it returned an error though. I'm not sure if a "if(bad stuff)", "print(blabla)" and "return" is how we throw errors in python. In R I just write "error(blabla)".

**Comment by tomweber-sas** [comment]
@AlexiaJM, I've pulled your code and tried it out both local and remote with both STDIO and IOM. There are some changes I've needed to make. I have the changes in a clone of your fork. 
This is my first time doing this and I'm not sure how to provide you those changes for you to incorporate into your fork, so we can merge this in.
I wasn't able to push to your fork. Do I need to fork yours instead of clone and then do a PR for your fork?
Am I supposed to be able to update the code in this PR (wherever that code is)? 
Sorry, first time newbie.

**Comment by AlexiaJM** [comment]
Hi Tomweber, I'm a newbie too, I'll try updating it with your version during my lunch break.

**Comment by tomweber-sas** [comment]
Well, here are the 2 files anyway. I see I can attach them here. You can incorporate my changes to your codebase. I'm sure there's got to be a better way than this :)


[Why I changed.txt](https://github.com/sassoftware/saspy/files/1022587/Why.I.changed.txt)
[sasioiom.txt](https://github.com/sassoftware/saspy/files/1022590/sasioiom.txt)
[sasiostdio.txt](https://github.com/sassoftware/saspy/files/1022591/sasiostdio.txt)

**Comment by tomweber-sas** [comment]
Sorry, one other thing to note (I forgot to add in the why I changed file). As this is a global option, we can't fail when making a remote connection if 'html' is set. So for that case I just write a note that 'html' isn't valid and use html5 instead so it works.

**Comment by AlexiaJM** [comment]
Thanks, added! The lower case was a good idea and all this try and catch, I wasn't familiar with how debugging is done in python.

**Comment by tomweber-sas** [comment]
Thanks! It looks like the two IO files are push in the wrong directory. The PR shows 5 files now, not 3. The IO files need to be under the saspy directory, not the root level. If you can fix that up, then I think we're ready to go. Thanks for working through this with me. I'm gonna have to start googling to see how this is really supposed to work :)

**Comment by tomweber-sas** [comment]
Ok, Jared moved the files over; he knows git more than I do :)
It all looks good now. If you're ok with this, all that's left is for you to follow the instructions in the ContributorAgreement.txt file (in the root saspy directory). Basically, if you agree to the stipulations (boiler plate stuff), then just add a commit with the signoff message in it, to this PR and I'll merge it for you. Getting close :)

**Comment by AlexiaJM** [comment]
Done :)

**Comment by tomweber-sas** [comment]
Awesome :)   And congratulations and thanks, for contributing to the project!

**Pull request merged**
