### PR TITLE
Only catch ImportError, don't ignore every error

### PR DESCRIPTION
**Pull request by moshekaplan**

### CODE REVIEW

**Comment by tomweber-sas** [comment]
These 3 seem fine. But I am trying to remember something in the back of my head. I'm not positive it was for this case or something else. There was a case where I needed to catch more than the one specific error, because the error being raised had changed in a newer version of python. I also think I remember that I couldn't code up the old and new (catching the 2 specific cases) because the new exception wasn't defined in the older version, and likewise with the old exception and new version of python. So, I have to leave it catching anything. I don't recall there being a 'general' error that caught the whole group of specific errors.

Again, I'm not sure that was for this case, though I kinda think it was. I will go dig through and see if I can verify what that was.

That's the only thing I want to verify before accepting this (these  3) changes. If this isn't the case I'm trying to remember, then I'll merge these in for you, no problem.

Thanks!
Tom

**Comment by moshekaplan** [comment]
I was under the impression that saspy only supported Python 3, so even if Python2 was different, that's no longer relevant.

**Comment by tomweber-sas** [comment]
Oh, it wouldn't be python2 vs. python3, as you say Py2 isn't supported. Whatever exception I'm remembering (from a year ago), would have been 3.2 (maybe) vs 3.5( maybe). Some dot release w/in Py3.
I haven't tracked it down yet though. too much task swapping the last couple of hours.

**Comment by moshekaplan** [comment]
Signed-off-by: Moshe Kaplan

**Pull request merged**
