### PR TITLE
Grammatical fix for failure messages: 'double check you|your settings'

### PR DESCRIPTION
**Pull request by Collinux**
Just a quick fix using `:%s/check you settings/check your settings/g` :)

### CODE REVIEW

**Comment by tomweber-sas** [comment]
Seriously? Do you know how many hundreds of times I've look at that! 
And I done speak good, fer real :)

Thanks! 
Tom

**Comment by tomweber-sas** [comment]
Hey, I've got a great idea, can you also change each sascfg.py to be sascfg_personal.py?
That would also be good as that is what everyone should really be using. The message was obviously implemented before I added the _personal file. So, since you're fixing up my other mistake, it'd be a good time to clean that up too. Happy to merge all that in!

Thanks!
Tom

**Comment by Collinux** [comment]
Sure no problem Tom!
Updated the PR (used `find ./ -type f -exec sed -i 's/sascfg.py/sascfg_personal.py/' {} \;`)

**Comment by tomweber-sas** [comment]
Great, thanks! I appreciate it. I'll merge this in. There were a lot more of those than I was expecting, and I see a few places where it still needs to say sascfg.py. But, those will need to be reworded as well to make sense. They were also written before there was an _personal.py. I'll need to rebuild the doc for most of this to take effect too, so I'll do that at the same time.

Thanks again for helping out!
Tom

**Pull request merged**
