### PR TITLE
Multi path libraries

### PR DESCRIPTION
**Pull request by metllord**
Base SAS supports libraries made up of multiple directories. This was not originally supported by the saslib function. This change allows saslib's path argument to be a string or a list of strings. Lists are parsed to match SAS's structure for multiple directory libraries.

Signed-off-by: Eric Stein ericst@wharton.upenn.edu

### CODE REVIEW

**Comment by tomweber-sas** [comment]
Hey, yes, that's a nice enhancement! I'm wondering why I didn't do that in the first place :) Works great. Thanks for contributing this!
Tom

**Comment by tomweber-sas** [comment]
Though there seems to be something a little out of whack with the file; see the conflict. I'm not sure why that is, just yet. I don't see anything in the diff like it's showing in the conflict. Can you check on that?
Thanks,
Tom

**Comment by tomweber-sas** [comment]
Oh, could be this, from your branch: This branch is 2 commits ahead, 558 commits behind sassoftware:main.
Can you get a current version of the file and use that for the PR?
Thanks!
Tom

**Comment by tomweber-sas** [comment]
Hey Eric, I've lost track of what you're trying to merge, with all of these file changes and diffs that have been going on here. It started as a clean 5 or so line change to support a list of libraries, and that code worked fine. Then the whole repository diffed, and now I'm seeing +753 −728 diff with a whole file reformatted, though only one file instead of all of them.
Can we get back to the 5 lines of code to implement the feature you've added, and then I can merge that change in t the existing code at main? 
Thanks!
Tom

**Comment by metllord** [comment]
Sorry about that. My editor's linter appeared to be a little overzealous. I'll turn it off and repush.

**Comment by tomweber-sas** [comment]
This is kinda getting worse. Is there any way you could just pull the code from saspy:main, add the 5 lines and make a new PR with nothing but that one change? 
Appreciate it :)
Tom

**Comment by metllord** [comment]
That seems to be the solution. I'll close this and resubmit once I figure out what's going on.

**Comment by tomweber-sas** [comment]
Cool, no trouble. Thanks!

**Pull request closed without merging**
