### PR TITLE
updated README.md and CONTRIBUTING.md layout

### PR DESCRIPTION
**Pull request by heoneal**
- made some updates to README.md to improve readability and markdown.
- Made note of platforms supported by saspy, which was missing MVS SAS.
- made some updates to CONTRIBUTING.md to improve readability. 
- included the ContributingAgreement.txt into CONTRIBUTING.md, this will allow the .txt to removed from the repo and for all contributing information to live in one location.

Signed-off-by: Holden O'Neal Holden.ONeal@sas.com

### CODE REVIEW

**Comment by tomweber-sas** [comment]
Hey Holden, this all seems good. I do have a couple things w/ the readme that I'll touch base with you on, offline. Other than that, this'll be good. 
Thanks,
Tom

**Comment by heoneal** [comment]
Hi Tom, see the latest for the updates!

**Comment by tomweber-sas** [comment]
gotcha .user written SAS code, not modules, then I can merge it :)

**Comment by heoneal** [comment]
Woops! Good catch.

**Comment by tomweber-sas** [comment]
Cool! Welcome to being a contributor :)

**Pull request merged**
