### PR TITLE
Support for SAS session encoding other than UTF8 and ssh example

### PR DESCRIPTION
**Pull request by spljaa**
I tested it on my box, with SAS running latin2 encoding and locale Polish.
There might be some trick with LST result if not HTML5. So I'm ok if you decide patch is not production ready.

Additionally I added example in cfg how to connect to remote SAS server using SSH. It works for password-less SSH. I do not know how password dialog could be handled.

### CODE REVIEW

**Comment by tomweber-sas** [comment]
Sorry not to have updated this earlier; we've been discussing this offline.
Yes, for ssh, I have that working already except for interrupt handling. I haven't yet been able to get the sigint to get across to the SAS process to trigger our interrupt handler. The interrupt does work when you run ssh from a terminal, but not as a sub process. And, I do have to use the -t option for ssh to work for me in general this way. 
As for encodings, although this may work for simple cases, there are more complicated scenarios in the future where this gets much more complicated. As Jupyter and python are both utf-8 and SAS supports utf-8, I'm inclined to leave this alone for now and will research it further as more of this unfolds.

**Comment by spljaa** [comment]
Ok. Agreed.
On my box "-t" was not needed. But it could be some configuration of ssh and sshd (both Fedora).
I tested encoding in simplest scenarios. It worked reasonably, so I wanted to share it. In case someone would strongly prefer to run SAS 9.4 using single byte encoding (I believe there could be reason for that)

**Comment by tomweber-sas** [comment]
pushed support for passwordless ssh and, as discussed, not changing encoding. So closing out this request.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
hey, with the new release of saspy, V2, we now have support for transcoding between python and SAS!
https://sassoftware.github.io/saspy/install.html#configure-saspy

**Comment by spljaa** [comment]
Awesome. I did not have enough time to play with it. New version looks really powerful.

**Pull request closed without merging**
