### PR TITLE
make authcode default; simplify prompting if authcode supplied

### PR DESCRIPTION
**Pull request by jld23**
Currently the user has to enter 'authcode' or 'userid' before they can continue.
I modified the code to make 'authcode' the default, if the user submits and empty string, authcode is assumed

The other change by passes all the prompting is the user provides an authcode.

Both changes are contained in the one file.

### CODE REVIEW

**Comment by tomweber-sas** [comment]
That diff is confusing. is this the only change:
266c266
<             msg += "Please enter which one you want to enter next. Type one of these now: [default=authcode | userid]: "
---
>             msg += "Please enter which one you want to enter next. Type one of these now: [authcode | userid]: "
269,270d268
<                if code_pw == '':
<                   code_pw = 'authcode'
tom64-5>

That's what I'm seeing, trying to read between the difff that has the same code broken all up, so it's had to tell.

**Comment by jld23** [comment]
@tomweber-sas,
There are two changes.
1. is in line 264. It changes the if statement to consider both the length of the user and if an authcode is not None. If the authcode is present then no prompting is needed just apply it.
2. The change you pointed out has the effect that if a user presses `enter` instead of either 'authcode' or 'userid' then is assume authcode. I was trying to steam line the user experience since authcode appears to be preferred to userid and password for http connections.
3.

**Comment by tomweber-sas** [comment]
Yeah, I understand what they do, actually 1 is irrelevant, as that is already supported. It's the difff, and thus the contents of the file I was questioning. The diff isn't simply add 2 lines and update another, So, are there windows CR's or tabs or other junk in that file to cause to diff to be so wrong? I can add those lines to my file and the diff only shows the changes, not what this diff shows.
Can you fix your copy of the file, so it only diffs the differences? And, you can remove that first change, as authcode can't not be none at that point (that check is redundant), if it were set, this block of code wouldn't be executing and it would have just connected.
Thanks,
Tom

**Comment by jld23** [comment]
@tomweber-sas,
I pushed the changes.
There is a diff on line 291 -- You had two spaces that were removed by my editor and line 298 had a single trailing space.
I can add those back in if you want but the change in side-by-side looks more straightforward now.

**Comment by tomweber-sas** [comment]
That's better. Still has a couple lines that seem like there were garbage character in them. If they're still there, I'll clean them up, but maybe that diif is based upon you're previous, so it's showing them cleaned up? Either way, it's just a couple lines so you can just hit enter, if you're even in this prompting to begin with. Good deal :) Thanks Jared!

**Pull request merged**
