### PR TITLE
add run_sas.py script

### PR DESCRIPTION
**Pull request by damjankrstajic**

### CODE REVIEW

**Comment by tomweber-sas** [comment]
There you go :)  Now this looks right.

**Comment by damjankrstajic** [comment]
Thanks!

**Comment by tomweber-sas** [comment]
so, the first thing I tried was running w/ an input file ./x/y/z/code.sas and my log and list were ./code.log ./code.lst but I was expecting  ./x/y/z/code.log,  ./x/y/z/code.lst.  Do you think the output should be where the code is, not always current dir?

**Comment by damjankrstajic** [comment]
Agreed. I will change that.

Quoting Tom Weber ***@***.***>:

**Comment by tomweber-sas** [comment]
another thought is to have, maybe -c, for config def to use? Running this from the command line, allows the prompt for the config def to be displayed, and entered, and that works. But if you could specify which cfgname to use, on the command, that would be one more feature that would be good.

```
tom64-5> ./scripts/x.py -s misc/x.sas
log_fname is x.log
lst_fname is x.lst
Please enter the name of the SAS Config you wish to run. Available Configs are: ['default', 'SASgrid', 'http', 'httptest',
 'ssh', 'sshtun', 'sshrtun', 'httpfred', 'grid', 'tdi', 'tdi_cn', 'tdi_cn8', 'tdilat', 'oda', 'iomj', 'sdssas_cn',
'sdssas_u8', 'iomc', 'iomjwin', 'winiomj', 'winiomjwin', 'winlocal', 'gridiom', 'wingridiom', 'zos', 
'zos2', 'winzos', 'winzos2', 'sshtest', 'sshloc', 'sdssas', 'saskr', 'vb010', 'vb015', 'pune', 'notpune', 
'iomkr', 'httpviya', 'kevin', 'issue176', 'httpjason', 'itviya', 'carrie1', 'console', 'iomcom', 'iomcom_loc', 
'iom4', 'm5bug', 'spre34', 'sshprob', 'vbviya', 'vbviyaxx', 'vbviyapp', 'alex', 'dotat', 'dotav', 'dotap', 
'dotas', 'odadev', 'mahesh', 'viya_cn', 'procpy', 'procpy_cn', 'tdiexe7', 'tdiexe6', 'biff', 'sshsax', 'chris',
'wilbram', 'sso', 'SGF_Viya', 'dotat_cn'] sdssas
SAS Connection established. Subprocess id is 29071

No encoding value provided. Will try to determine the correct encoding.
Setting encoding to latin_1 based upon the SAS session encoding value of latin1.

SAS Connection terminated. Subprocess id was 29071
```

**Comment by tomweber-sas** [comment]
Nice, -r works just as expected w/ HTML output! That's sweet!
Can the parameters be case insensitive: -r html as opposed to having to be all uppercase (-r HTML)? Jud ass .upper():
if results_format.upper() == 'HTML':

**Comment by tomweber-sas** [comment]
And the output is now in the same dir as the source!

**Comment by damjankrstajic** [comment]
I would like to add -c config but the way I execute the code, I don't get asked for it. I don't have an example for it.

**Comment by tomweber-sas** [comment]
Ah, you would just use it kinda like as follows, if it was provided (based on how I see the other options done):
```
    parser.add_argument('-c', '--cfgname', help='name of the Configuration Definition to use for the SASsession')



    if options.cfgname is None:
        sas_session = saspy.SASsession()   
    else:
        sas_session = saspy.SASsession(cfgname=options.cfgname)


```

**Comment by damjankrstajic** [comment]
OK. I can add that, but I cannot test it.

**Comment by tomweber-sas** [comment]
I just did :), you can too, just add another config def in your sascfg_persional.py file: https://sassoftware.github.io/saspy/install.html#sascfg-personal-py-details
Then you'll see the same prompt, and /w -c you can say which one. Give it a try,

```
tom64-5> ./scripts/x.py -s misc/x.sas -c ssh
log_fname is misc/x.log
lst_fname is misc/x.lst
SAS Connection established. Subprocess id is 29860

No encoding value provided. Will try to determine the correct encoding.
Setting encoding to latin_1 based upon the SAS session encoding value of latin1.

SAS Connection terminated. Subprocess id was 29860
```

**Comment by tomweber-sas** [comment]
This is looking really good. Need doc next. I just pushed out the API.rst (saspy/doc/source/API.rst) that has the Script section stubbed in. I think you can update your fork with that change, and then add documentation to that section explaining this script. I'm not sure about how to update your fork with these newer changes in my repo, but you can google it. I don't do that kind of thing, so I have to google those cases that aren't the usual thing. But, with doc and the code you have so far, I think it will be in good shape to merge in. It's working as expected!

**Comment by damjankrstajic** [comment]
Added -c option without being able to properly test it. I am not sure that I cannot use any other sascfg other than ODA with SAS OnDemand for Academics.

**Comment by damjankrstajic** [comment]
I am not sure that I absolutely understand you regarding the documentation. I can see on the main branch that api.rst has been updated. I suggest that you merge my code if it works correctly on your side, and then we can look into modifying documentation. As I say, I am not sure what you expect me to do. I would like to finish the job properly.

**Comment by tomweber-sas** [comment]
Well, it's just another file to update in the PR. Merging both the code and the doc is proper. But, as it will be easier to just merge in the code then let you open another for the doc, since the change to that file is new and not in your fork, we can just do it that way in two steps. Is the code up to where you want it to be? ready to merge? I've been jumping back and forth on other things.

**Comment by tomweber-sas** [comment]
oh, as for testing out 2 config defs, you can just copy the one you have and give it a different name (they can be the same so they actually work). then you have more than 1 and if you don't say which one, it will prompt you. easy. don't forget to add the copies name to the SAS_config_names list.

```
SAS_config_names = ['a','b']

a = { ... }  # whatever you have

b = { ... } # same as a above, just a copy
```

**Comment by damjankrstajic** [comment]
The code is ready for merge.

**Comment by damjankrstajic** [comment]
How much information do I need to put into the documentation? Any example. Thanks.

**Comment by tomweber-sas** [comment]
Well, it doesn't have to be a book. I would explain what it is, what it's used for; use cases. Mention the options and what they control. You can provide some examples, or not. In the https://sassoftware.github.io/saspy/advanced-topics.html# section of the doc, I have some short ones, and some long ones. It just depends on the topic. You can also see how to format things in those examples, especially if you show code examples or any kind of output; like using 
```
format code here in this way; rst file have their ow formating syntax
```

Just explain what you would want someone to understand about the script so they know how to use it appropriately.

**Pull request merged**
