### PR TITLE
Add support for ~/.authinfo to IOMCOM

### PR DESCRIPTION
**Pull request by hhubbell**
The Java IOM access method supports reading username/password credentials from a ~/.authinfo file.  The spec for this file can be found here: https://documentation.sas.com/api/docsets/authinfo/9.4/content/authinfo.pdf.

This file uses the following format:
```
AUTHKEY username USERNAME password PASSWORD
```

Where the user can define the `AUTHKEY`, `USERNAME`, and `PASSWORD` attributes.

This PR was spawned from a comment in issue #237

### CODE REVIEW

**Comment by tomweber-sas** [comment]
Hey, cool. Yeah, both IOM and HTTP access methods support this. I know you like throwing exceptions :) but I just double checked, and both the others revert back to prompting for user/pw if the authkey isn't found, as opposed to failing at that point. I'm not overly concerned if this is different, but though I'd mention it to see what you thought. If you want to throw that error, I'm ok and can merge it in as is. Your call.

Thanks!
Tom

**Comment by hhubbell** [comment]
Hi Tom,

Good point - I want to follow the library convention as closely as possible.

Actually, it looks like the COM access method doesn't currently prompt for credentials at all. I added that functionality as well to bring it in line with the other methods.

**Comment by tomweber-sas** [comment]
Cool. I'll pull this and try it out, I'm sure you have it working and all, but just due diligence. Then I'll merge it in. 
Thanks!
Tom

**Comment by tomweber-sas** [comment]
Well, I found a couple issues, so I'm glad I tried it out. The first is that this is failing for me; yeah, bad news first I suppose :)
I debugged it and found the following (parsing the lines isn't handling white space, it can only handle one single blank between words)

I was trying this:
```
import saspy
sas = saspy.SASsession(cfgname='iomcom_auth') #, authkey='', omruser='user', omrpw='pw')
sas
```
```
> c:\programdata\anaconda3\lib\site-packages\saspy\sasiocom.py(85)_set_authinfo()
-> authfile = os.path.expanduser(os.path.join('~', '_authinfo'))
(Pdb)
> c:\programdata\anaconda3\lib\site-packages\saspy\sasiocom.py(89)_set_authinfo()
-> with open(authfile, 'r') as f:
(Pdb)
> c:\programdata\anaconda3\lib\site-packages\saspy\sasiocom.py(90)_set_authinfo()
-> reader = csv.reader(f, delimiter=' ')
(Pdb)
> c:\programdata\anaconda3\lib\site-packages\saspy\sasiocom.py(93)_set_authinfo()
-> authline = next(filter(lambda x: x[0] == self.authkey, reader), None)
(Pdb)
> c:\programdata\anaconda3\lib\site-packages\saspy\sasiocom.py(95)_set_authinfo()
-> if authline is None:
(Pdb) authline
['saspy1', '', '', '', '', '', '', '', '', 'user', 'id', '', '', '', '', '', '', '', '', '', '', '', 'password', 'pw']
(Pdb) n
> c:\programdata\anaconda3\lib\site-packages\saspy\sasiocom.py(97)_set_authinfo()
-> elif len(authline) < 5:
(Pdb)
> c:\programdata\anaconda3\lib\site-packages\saspy\sasiocom.py(103)_set_authinfo()
-> self.user = authline[2]
(Pdb) n
> c:\programdata\anaconda3\lib\site-packages\saspy\sasiocom.py(104)_set_authinfo()
-> self.pw = authline[4]
(Pdb)
--Return--
> c:\programdata\anaconda3\lib\site-packages\saspy\sasiocom.py(104)_set_authinfo()->None
-> self.pw = authline[4]
(Pdb) authline[2]
''
(Pdb) authline[4]
''
(Pdb) authline[8]
''
(Pdb) authline[7]
''
(Pdb) authline[9]
'user'
(Pdb)
```
So it was failing w/ no userid provided:
```
com_error                                 Traceback (most recent call last)
<ipython-input-1-58ab49ebc244> in <module>()
      1 import saspy
----> 2 sas = saspy.SASsession(cfgname='iomcom_auth') #, authkey='', omruser='carynt\dbitest2', omrpw='Dbigrp1')
      3 sas

C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasbase.py in __init__(self, **kwargs)
    342             self._io = SASsessionIOM(sascfgname=self.sascfg.name, sb=self, **kwargs)
    343         elif self.sascfg.mode == 'COM':
--> 344             self._io = SASSessionCOM(sascfgname=self.sascfg.name, sb=self, **kwargs)
    345         elif self.sascfg.mode == 'HTTP':
    346             self._io = SASsessionHTTP(sascfgname=self.sascfg.name, sb=self, **kwargs)

C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasiocom.py in __init__(self, **kwargs)
    191         self._log = ''
    192 
--> 193         self.pid = self._startsas()
    194 
    195     def __del__(self):

C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasiocom.py in _startsas(self)
    245         self.keeper.AddObject(1, 'WorkspaceObject', self.workspace)
    246         self.adodb.Open('Provider={}; Data Source=iom-id://{}'.format(
--> 247             self.sascfg.provider, self.workspace.UniqueIdentifier))
    248 
    249         return self.workspace.UniqueIdentifier

C:\ProgramData\Anaconda3\lib\site-packages\win32com\client\dynamic.py in __getattr__(self, attr)
    514                         debug_attr_print("Getting property Id 0x%x from OLE object" % retEntry.dispid)
    515                         try:
--> 516                                 ret = self._oleobj_.Invoke(retEntry.dispid,0,invoke_type,1)
    517                         except pythoncom.com_error as details:
    518                                 if details.hresult in ERRORS_BAD_CONTEXT:

com_error: (-2147352567, 'Exception occurred.', (0, '', '<?xml version="1.0" ?><Exceptions><Exception><SASMessage severity="Error">An anonymous user cannot perform this function (calling interface Workspace_1_0). Please supply a userid and password when connecting to the server.</SASMessage></Exception></Exceptions>', None, 0, -2147024891), None)
```

The other thing I noticed was that I can't provide or override any keys in the SASsession() method. That's another incompatibility between COM and all of the other access methods. 

If you just want to fix the parser for this, and worry about supporting config def parms in SASsession in a different PR, that's fine. Or you can add it here, whatever you like.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
Thanks Harry, I'll try this out tomorrow. My main concern, after functioning, is that there's no dependency on anything not in the python standard library. Your code still falls in there so that's cool. 
Expecting to validate and merge this in tomorrow.

Holy molly, St. Louis won! Cripes!

**Comment by hhubbell** [comment]
Hi Tom,

Cool, yeah this `shlex` module in the stdlib is pretty neat.  Much better than the `csv` with space delimiter workaround - I should have avoided that from the start.

I will take a look at the override issue and submit another PR for that.

Everyone is a little bummed up here in Boston today!

**Comment by tomweber-sas** [comment]
Yeah, I bet! Sorry for your loss :)

I ran this and it all works except for one case, where the userid in the authinfo file is domain\user. The slash is being eaten, so the id being passed is 'domainuser' instead of 'domain\user', which of course fails authentication. It works if typed in as domain\user when prompted or if that's specified in the config def. for omruser. If you tweak it to fix that case, I think it will be good to merge.  

Thanks,
Tom

**Comment by hhubbell** [comment]
Just updated the code to not read backslashes as escape sequences.

Do you have a list of examples that I could create test cases for?

**Comment by tomweber-sas** [comment]
Hey Harry, this looks good. The following is my authinfo file, with most stuff changed, of course.
But, basically I have 3 forms of userid and whitespace for readability. You code is now working with all of this.

user
user@domain
domain\user

```
saspy1         user user             password mypassword
iomjwin        user user@domain      password mypassword
gridiom        user user             password mypassword
zos            user otheruser        password mypassword
default        user otusr@domain     password mypassword
host rdcgrdc   user sastpw           password mypassword
iomcom         user domain\user2     password mypassword
iomcom2        user user2@domain     password mypassword
```

**Pull request merged**
