### PR TITLE
Create run_sas.py

### PR DESCRIPTION
**Pull request by damjankrstajic**

### CODE REVIEW

**Comment by tomweber-sas** [comment]
No, you don't edit that file (ContributorAgreement.txt), those are just instructions. You would type in that line (the signed off by) in one of these comments in this PR. But that would also mean you provide the script you want to add. That's the file to add to this PR. Are you still working on that?

Thanks,
Tom

**Comment by damjankrstajic** [comment]
Noted. Apologies for creating confusion. I have nearly finished  
run_sas.py script, and have committed several versions of it. I just  
need to add -r option and the code is finished.

Quoting Tom Weber ***@***.***>:

**Comment by damjankrstajic** [comment]
I executed 
git clone git@github.com:damjankrstajic/saspy.git
and committed run_sas.py in the scripts folder.
I have now executed tig command and see that I am in the main branch ([main] {origin/main} {origin/HEAD})
Apologies.

**Comment by damjankrstajic** [comment]
What is the best way forward?

**Comment by damjankrstajic** [comment]
Apologies for asking a stupid question, but how do I clone my branch with "git clone"?

**Comment by tomweber-sas** [comment]
No problem, I don't really do PR's to other repos so I'm no expert on that either. Did you fork saspy, and then you cloned your fork of it and that's where you're pushing? That is how I think it works easiest. I have a clone of saspy directly, so I just push and pull from the command line from my linux system 9but then, it's my repo). I think you would clone your fork and do that too. For the PR, I would use the github UI in a browser to fork and do the PR from that fork,, as I don't know command line for that cuz I never do it.
I think you would work in the main branch of your fork, so that when you try to do the PR it's from main of your clone, to the main of saspy.
Hope that makes sense. Again, no problem if it take a little to figure this out. Usually others who do PR's here already know how, so I don't even have that much experience telling them how. We'll figure it out.

**Comment by tomweber-sas** [comment]
ok, I see your's is a fork of saspy. So then you cloned it, so you're pushing to it, so that's right. And, the changes you really want are in main, it seems. So, I think you just be in the main branch and click open PR to push upstream. Maybe close this one, as it was from that patch1 branch? I think you're close.

**Comment by damjankrstajic** [comment]
Thanks Tom for your understanding. I suggest the following course of actions:
a) I close PR in which I changed ContributorAgreement.txt. I presume that just closing PR is sufficient.
b) You merge the current version of run_sas.py which has missing -r option
c) I create a new PR in which I finish run_sas.py (add -r option)

I will understand if you disagree and I won't do anything until I hear from you.

**Comment by tomweber-sas** [comment]
I think closing this one and opening one with the code you're looking to have merged in is the easiest thing to do. You can open a new one with what yo have, and you can add changes to that, as you work on it. I'll need to do some testing and verifications too, so that's kinda the normal flow; you can enhance and change things before the PR is finally merged in. I would open the new one from the main branch of your fork.

**Comment by damjankrstajic** [comment]
I cannot pull a new request.

**Comment by tomweber-sas** [comment]
how do you mean?

**Comment by damjankrstajic** [comment]
On the webpage https://github.com/sassoftware/saspy/pulls I click "New  
pull request" and then I am forwarded to the webpage  
https://github.com/sassoftware/saspy/compare where the button "Create  
pull request" is disabled.

Quoting Tom Weber ***@***.***>:

**Comment by tomweber-sas** [comment]
You need to do it from your fork, where you're new code is. https://github.com/damjankrstajic/saspy
make sure you're in main, and there's a line that says this:
This branch is 3 commits ahead, 1 commit behind sassoftware:main.         then: Contribute
Click contribute pull down and you'll see the compare and open pull request stuff you're expecting
https://github.com/sassoftware/saspy/compare/main...damjankrstajic:main

**Pull request closed without merging**
